### PR TITLE
Fix bytecompiler warnings

### PR DESCRIPTION
**Pull request by s-kostyaev**
Based on #1 and #2, review it first.
Fix byte compiler warnings. Also I issue opened with undefined function. And let docstrings for you 😄

### CODE REVIEW

**Comment by s-kostyaev** [comment]
Rebased onto latest master

**Comment by alan-w-255** [comment]
Thank you very much for your PR. But it seems that the submitted code is not formatted?

**Comment by s-kostyaev** [comment]
All code reformatted.

**Comment by alan-w-255** [comment]
Thank you so much. My code is a mess. 😄

**Comment by s-kostyaev** [comment]
For that community is - to make someone's code less messy 😄

**Pull request merged**
